name: Publish canary
on: 
  pull_request: 
    branches:
      - develop

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"
          registry-url: 'https://registry.npmjs.org'

      - name: Bootstrap packages
        uses: ./.github/actions/cache-bootstrap

      - name: Build Packages
        run: yarn build

      - name: "Get Branch Name"
        env:
          IS_PR: ${{ github.EVENT_NAME == 'pull_request' }}
        run: |
          if ${IS_PR}; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else
            BRANCH_NAME="${GITHUB_REF##*/}"
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
      - name: Format Branch name
        run: echo "Name -> ${{ env.BRANCH_NAME }}"

      # - name: Publish Canary
      #   run: lerna publish --yes --canary --preid ${{steps.format-branch.outputs.result}} --force-publish="*"
      #   env:
      #     # TODO: Add token
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}