name: Create Linear Issue on Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types: [opened]

jobs:
  create-linear-issue-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create the Linear Issue
        id: createIssue
        uses: ctriolo/action-create-linear-issue@v0.5
        with:
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          linear-team-key: "SUP"
          linear-issue-title: ${{github.event.pull_request.title}}
          linear-issue-description: ${{github.event.pull_request.body}}
          linear-attachment-url: ${{github.event.pull_request.html_url}}
          linear-attachment-title: ${{github.event.pull_request.title}}
