name: Send release notifications
on:
  release:
    types: [published]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Discord Notification
        id: notification
        run: message=$(node scripts/discord-notis.js '${{ github.event.release.tag_name}}' '${{ github.event.release.html_url }}') && echo ::set-output name=message::${message//$'\n'/'%0A'}

      - name: Discord Notification
        id: discord-notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ${{ steps.notification.outputs.message }}
