name: Staging Release and publish

# Only trigger, when the build workflow succeeded
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "www/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Staging Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: version staging packages
        run: yarn version:staging-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish staging packages
        run: yarn release:staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release Pull Request
      #   uses: changesets/action@v1
      #   with: 
      #     version: yarn version:staging-snapshot
      #     publish: yarn release:staging
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}