name: Performance tests
on:
  pull_request:
  push:

jobs:
  simple-performance-test:
    env:
      NODE_ENV: CI
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      REDIS_URL: redis://localhost:6379
      DATABASE_URL: "postgres://postgres:postgres@localhost/cli-test"
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: cli-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: cli-database

      - name: Install Medusa cli
        run: npm i -g @medusajs/cli@preview

      - name: Create Medusa project
        working-directory: ..
        run: |
          medusa new cli-test --skip-db --skip-migrations --v2 --branch chore/ci-perf-tests

      - name: Enable Corepack
        run: corepack enable

      # - name: Install new app dependencies (via resolutions)
      #   run: rm package-lock.json && yarn install --no-immutable
      #   env:
      #     YARN_ENABLE_IMMUTABLE_INSTALLS: false
      #   working-directory: ../cli-test

      - name: Run migrations
        run: npx medusa db:migrate
        working-directory: ../cli-test

      - name: Run seed
        run: npx medusa exec ./src/scripts/seed.ts
        working-directory: ../cli-test

      - name: Create admin user
        run: npx medusa user -e test@test.com -p password -i admin_123
        working-directory: ../cli-test

      - name: Run development server
        run: npx medusa develop &
        working-directory: ../cli-test

      - name: Testing development server
        uses: ./.github/actions/test-server

      - name: Starting medusa
        run: npx medusa start &
        working-directory: ../cli-test

      - name: Wait for live server response
        shell: "bash"
        run: ./integration-tests/scripts/cli/wait-for-server-live.sh

      - name: Set up K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        env:
          K6_REGION_ID: "reg_europe"
          K6_PUBLISHABLE_KEY: "pk_123456789"
        with:
          path: scripts/small-dtc-local.js
        continue-on-error: true # Continue to post results even if test fails

      - name: Kill server
        shell: "bash"
        run: kill -9 $(lsof -t -i :9000)

      - name: Post PR comment
        if: always()
        uses: thollander/actions-comment-pull-request@v2
        with:
          file-path: summary.html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
