name: Deploy Preview

on: [pull_request]

jobs:
  deploy-preview:
    env:
      NODE_ENV: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get PR sha
        id: get_pull_request_sha
        run: |
          pull_request_sha=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH" | cut -c1-8)
          echo "pull_request_sha=${pull_request_sha}" >> $GITHUB_OUTPUT
          echo $pull_request_sha

      - name: Neon Database Create Branch Action
        uses: neondatabase/create-branch-action@v3
        id: create_branch
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{steps.get_pull_request_sha.outputs.pull_request_sha}}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.PG_USERNAME }}
          password: ${{ secrets.PG_PASSWORD }}

      - run: echo ${{ steps.create-branch.outputs.project_id}}
      - run: echo ${{ steps.create-branch.outputs.branch_id}}

      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.PREVIEW_REPO_ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/olivermrbl/heroku-neon-medusa/actions/workflows/deploy-preview.yml/dispatches \
          -d '{"ref":"main", "inputs": { "heroku_app_name": "preview-${{steps.get_pull_request_sha.outputs.pull_request_sha}}", "db_url":"${{ steps.create_branch.outputs.db_url}}/neondb", "pull_request_sha": "${{steps.get_pull_request_sha.outputs.pull_request_sha}}" }}'